name: Daily Predictions Update

on:
  schedule:
    # Tous les jours à 00:00 heure de Paris (22:00 UTC)
    - cron: '0 22 * * *'
  workflow_dispatch:  # Permet de lancer manuellement le workflow

jobs:
  update-predictions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright dependencies
      run: |
        playwright install-deps
        playwright install chromium
        
    - name: Run scraper
      run: python test.py
      
    - name: Build frontend
      run: python build.py
      
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add football_predictions_*.json football_predictions_*.html dist/
        git commit -m "Update predictions for $(date +'%Y-%m-%d')" || exit 0
        git push 